name: 'Camp Rhino - Port Elizabeth, South Africa'
logo_image_path: /uploads/logo.png
logo2_image_path: /uploads/logo2.png
main_image: /uploads/header-image.jpg
phone: (404) 205-2974
email: missionarycoffey@gmail.com
facebook: 'https://www.facebook.com/camprhinoPE'
twitter:
youtube:
instagram:
address: P.O. Box 442
address2:
mission_board_image: 'http://sitesforchurch.s3.amazonaws.com/vision.jpg'
project_south_africa_image: /uploads/psa.jpg
City: Alpharetta
State: GA
Zip: '30009'
lattitude: '38.949608'
longitude: '-87.744489'
map_zoom_level: 14
main_blog_image: /uploads/1.jpg
main_sermon_image: /uploads/2.jpg
default_calendar_image: /uploads/hartwell.jpg
Google_calendar_id: leonhart4@gmail.com
tinyletter: 'https://tinyletter.com/pastorryanhayden'